### ISSUE TITLE
 query about leading spaces and non-breaking spaces 

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/ebookmaker#122]
in #121 @asylumcs   has a query about leading spaces and non-breaking spaces

**Comment by eshellman** [comment]
@asylumcs With regard to leading spaces, I see no such spaces in the submitted file. Do you have a line number to reference?

**Comment by eshellman** [comment]
for 69069

**Comment by asylumcs** [comment]
Here is what the uploader intended based on their text file. Line numbers are shown:
![Screen Shot 2022-10-03 at 4 52 03 PM](https://user-images.githubusercontent.com/37535965/193700361-860ee921-8ad9-44e2-849b-14973e19810e.png)

Here is what shows up in the HTML:
![Screen Shot 2022-10-03 at 4 56 37 PM](https://user-images.githubusercontent.com/37535965/193700424-278f1616-ebeb-46e0-9dbe-9d92c7ebbefa.png)

And here is why it's happening (line numbers shown):
![Screen Shot 2022-10-03 at 4 55 47 PM](https://user-images.githubusercontent.com/37535965/193700481-5488d064-9bf0-4e69-a7d9-327ffe97ae2b.png)

Notice the pale orange squares are regular spaces and the plain white spaces are non-breaking spaces. The line starting with id="id00426" is indented once because of the paragraph indent and then further because of the hard spaces before "Pitämään". 

No clue if there's a way to do this with a program, but if there are leading spaces I would probably use a <div> and apply hard spaces consistently to each line. This uploader didn't provide an HTML file and relied on what ebookmaker would do.

**Comment by eshellman** [comment]
The code that manages this hasn't changed in 13 years, so I'm guessing that messing with it might do more harm than good.
`
RE_INDENT = re.compile(r"^\s+")
    def preformat(line):
        m = RE_INDENT.match(line)
        if m:
            # 0x0a   no-break space
            # 0x2003 em-space
            # 0x2007 figure space
            line = ('&#xa0;' * (m.end() - m.start())) + line[m.end():]
        return line + "<br />\n"
`
This would be fine, except the verse isn't scored high enough by the verse detector  for the paragraph to be put in a `pre` element.
