### ISSUE TITLE
TOC missing in generated EPUBs

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#167]
The TOC that should be coming from toc.xhtml is not appearing in EPUB3s. This is not the HTML TOC that is often included in the file, but the one that's specific to the EPUB. Verified on a Kobo and a Nook.

**Comment by eshellman** [comment]
I don't understand. Is this a particular book? Books I've looked at look great on Calibre and Apple books. I don't have a nook or a kobo.

**Comment by asylumcs** [comment]
It's every book I tested, new and old. Other's report the same thing. If you click on the book's TOC you get nothing. It used to work just fine.

**Comment by eshellman** [comment]
The only change we've made in epub3 since september has been to adopt svg covers. The SE ebooks replace svg with png for kobo. Maybe that invokes the EPUB2 renderer, which needs the NCX file? Maybe you can test one of our EPUB3 files made with 0.12.21

**Comment by eshellman** [comment]
[68836-images-epub3 copy.zip](https://github.com/gutenbergtools/ebookmaker/files/10841906/68836-images-epub3.copy.zip)
try this one (just change .zip to .epub)

**Comment by eshellman** [comment]
According to Kobo support, this is due to all sideloaded files being processed by the RMSDK (Adobe) rendering engine rather than the Kobo engine. Kobo is looking at addressing this issue in future versions of their software.

However, based on consultation with @gbnewby , PG considers adding an NCX file to our EPUB3 to be desirable. I estimate this will not be hard to code, but testing the resulting files introduces a number of issues. Will you be able to do testing @asylumcs ?

**Comment by asylumcs** [comment]
I can test on a newer Kobo and an older Nook.

**Comment by eshellman** [comment]
0.12.30
