### ISSUE TITLE
Ebookmaker is not creating a mobi file.  

### ISSUE THREAD

**Issue by okrick** [gutenbergtools/ebookmaker#80]
[Ebookmaker](https://ebookmaker.pglaf.org/) did not create a mobi file for the attached project.

The message did not indicate any errors:

>  Project Gutenberg Online Ebookmaker
> 
> Starting ebookmaker: Running ebookmaker --make=epub --make=kindle --make=html --max-depth=3 --output-dir=/htdocs/ebookmaker/cache/20210424183418 --title="UnknownTitle" --author="UnknownAuthor" --ebook="10001" file:///htdocs/ebookmaker/cache/20210424183418/tot.html
> 
> Done: ebookmaker ended with a successful exit code. This does not mean all desired output was successfully generated. The output.txt file provides detail on the processing that occurred, and any error or informational messages. Please follow this link to view the input file you uploaded (possibly it was renamed) and any output files. This link will stay available for a day or two:
> 
>     https://ebookmaker.pglaf.org/cache/20210424183418

There were no W3C errors in the HTML.  I coded some x-ebookmaker-drop to prevent some headers from appearing on top of the following text.  Seemed to work fine in the epub version.

[tot.zip](https://github.com/gutenbergtools/ebookmaker/files/6371058/tot.zip)

**Comment by asylumcs** [comment]
> On Apr 24, 2021, at 9:53 PM, okrick ***@***.***> wrote:
> 
> Ebookmaker did not create a mobi file for the attached project (tot.zip)…

It fails because the HTML file has an h2 element inside a div with class x-ebookmaker-drop.

  <div class='x-ebookmaker-drop'>
      <h2>A Nice Day</h2>
  </div>

Those three lines with .x-ebookmaker-drop { } in CSS will replicate the problem of mobi not being generated.

Since the 'x-ebookmaker-drop' class tells ebookmaker to remove an element and its descendents from ebook builds, I’m not surprised that the TOC fails to build, which causes the mobi build to fail.

Hope this helps.

—Roger

**Comment by okrick** [comment]
Roger,

Thank you for confirming that.  I woke this morning with a less roundabout
way of accomplishing what I was trying to do in mind.

I'll make the fix and rerun it.

Thank you,

Rick

**Comment by eshellman** [comment]
Thanks Roger and Rick!
